### ISSUE TITLE
OpenCVBridge

### ISSUE THREAD

**Issue by mcd8604** [GeertLitjens/ASAP#1]
I am using patchToMat as follows:
```
Patch<uchar> p = input->getPatch<uchar>(...);
Mat m = patchToMat(p);
```
I was getting compilation errors:
```
error C2440: 'const_cast' : cannot convert from 'const unsigned char *' to 'double *'
```
I made the following change locally and it is fixed:

```
 -      T* data = const_cast<double*>(patch.getPointer());
 +      T* data = const_cast<T*>(patch.getPointer());
```
I haven't tested it yet since I'm using 3 channels anyway. Was there a reason for the double cast?

**Comment by GeertLitjens** [comment]
Hi mcd8604,

Doesn't seem to be anymore, I changed it locally also and will add your change with the next git push. Thanks for pointing it out!
