### ISSUE TITLE
Compiling on Ubuntu

### ISSUE THREAD

**Issue by bchidest** [GeertLitjens/ASAP#19]
I've been following the process for compiling ASAP using CMake on Ubuntu (defining each LIBRARY and INCLUDE variable as they come up after each Configure iteration), and I think I've managed to do that correctly. However, I am stuck with the following error:

CMake Error at core/CMakeLists.txt:12 (target_compile_features):
  target_compile_features no known features for CXX compiler

  "GNU"

  version 4.8.4.

Is a different version of g++ required? Is it something to do with c++11? I'm currently using CMake 3.2.2, if that might be relevant to the issue.

**Comment by GeertLitjens** [comment]
Hi, I compiled it today on Kubuntu 16.04 LTS, which has a G++ of 5.4. I haven't used the 4.8 versions in years. Could you try updating your gcc toolchain?

**Comment by chengchen77** [comment]
I am getting a similar error when I try to compile ASAP using CMake (3.6.3) and VS 2013 on Windows:

CMake Error at core/CMakeLists.txt:12 (target_compile_features):
  The compiler feature "cxx_generalized_initializers" is not known to CXX
  compiler

  "MSVC"

  version 18.0.21005.1.

Any suggestion for solving this issue?

**Comment by GeertLitjens** [comment]
As far as I understood this feature was added to VS2013 in Update 3, so I recommend trying to update your  VS

**Comment by chengchen77** [comment]
I installed the Update 5 and the issue was solved. Thank you for the suggestion.
