### ISSUE TITLE
Cannot find Openslide on Ubuntu 16.04

### ISSUE THREAD

**Issue by CaseyConger** [GeertLitjens/ASAP#20]
I am trying to install ASAP on ubuntu 16.04 and I get the following error following cmake command

casey@casey-K401LB:~/Downloads/ASAP-1.6$ cmake .
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   date_time
--   filesystem
--   program_options
--   regex
--   system
--   thread
--   chrono
--   atomic
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find OPENSLIDE (missing: OPENSLIDE_LIBRARY OPENSLIDE_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  cmakemodules/FindOPENSLIDE.cmake:14 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:58 (FIND_PACKAGE)

-- Configuring incomplete, errors occurred!
See also "/home/casey/Downloads/ASAP-1.6/CMakeFiles/CMakeOutput.log".
See also "/home/casey/Downloads/ASAP-1.6/CMakeFiles/CMakeError.log".

However, I have installed openslide using apt-get:
casey@casey-K401LB:~/Downloads/ASAP-1.6$ sudo apt-get install openslide-tools 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
openslide-tools is already the newest version (3.4.0-1build1).

Any help would be greatly appreciated.

**Comment by CaseyConger** [comment]
Just had to manually put in the directory and it worked.

**Comment by indestinee** [comment]
@CaseyConger put what in what directory please, I have same problem,
CMake Error at CMakeLists.txt:5 (cmake_policy):
  Policy "CMP0071" is not known to this version of CMake.


CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find OPENSLIDE (missing: OPENSLIDE_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  cmakemodules/FindOPENSLIDE.cmake:14 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:68 (find_package)

**Comment by LindaSt** [comment]
> Just had to manually put in the directory and it worked.

Which directory did you have to "put in" and how?
