### ISSUE TITLE
Compiling on Windows x64 with msvc2013

### ISSUE THREAD

**Issue by pisarik** [GeertLitjens/ASAP#21]
Hello! I compiled all 3rd party libraries. Then successfully added them to CMake paths, configuration was done, and then project was generated for msvc2013, but there is warnings like a

```
CMake Warning (dev) at core/CMakeLists.txt:6 (ADD_LIBRARY):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target "core" links to target "Boost::disable_autolinking" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
This warning is for project developers.  Use -Wno-dev to suppress it.
```
And other warnings related to links to boost. If I try to compile project, then I getting:
`error LNK1104: cannot open file 'Boost::disable_autolinking.lib'` from core module

So I should disable auto linking. I never worked with boost before.
I can't find official documentation related to auto-linking in boost, except little mentions about it, but I found several solutions on stackoverflow and [other sites](http://www.npcglib.org/~stathis/blog/2012/05/25/coding-tip-disable-autolinking-in-boost/).

Solutions say that for disabling auto-linking I should define macros `BOOST_ALL_NO_LIB`, but I can't understand where is I should define it. I tried to define it in preprocessor defines of core project, uncomment this define in `boost/config/user.hpp`, also tried to recompile boost with following options:
`b2 -j 4 --toolset=msvc-12.0 addreess-model=64 --build-type=complete define=BOOST_ALL_NO_LIB stage --stage-dir=lib/x64`

But no one solution is helped. Also I noticed, that `Jamroot` file, which configuring boost build, has following lines:
```
# Disable auto-linking for all targets here, primarily because it caused
      # troubles with V2.
      <define>BOOST_ALL_NO_LIB=1
```

It looks like auto-linking disabled by default.
Boost version: 1.63.0
CMake version: 3.3.1

**Comment by pisarik** [comment]
Oh.. The problem was in CMake. I updated one to latest version and the problem is gone.
I spent 2 days on this problem:\ But the problem written here helped me to think about cmake version:D

Thank you!

**Comment by GeertLitjens** [comment]
I'll update the readme file to reflect you should use the latest CMake

**Comment by FreeAJust** [comment]
@pisarik , Hello!
I have some trouble in compiling the ASAP in msvc2013, May I ask you questions? 

- Do you know how to install libjpeg?
In README, there is a link as libjpeg (http://libjpeg.sourceforge.net/). But the file I downloaded can't not make or cmake , I'm confused how to set JPEG_LIBRARY and JPEG_INCLUDE_DIR. Can you tell me how to do?


I'm appreciate if you can help, thanks a lot!
