### ISSUE TITLE
Unresolved external symbol jpc_decode

### ISSUE THREAD

**Issue by pisarik** [GeertLitjens/ASAP#22]
Hello! I compiled all 3rd party libraries. Then successfully added them to CMake paths, configuration was done, and then project was generated for msvc2013, but when I try to compile, then I get single link error from `multiresolutionimageinterface` module:

`error LNK2001: unresolved external symbol jpc_decode JPEG2000Codec.obj`

As I understand this problem related to jasper library. Jasper 2.0.10 was successfully built.
Is it сompatibility problems? And should I compile older version of Jasper?

**Comment by GeertLitjens** [comment]
Dear pisarik, it's hard for me to say. I'm using 2.0.0 as far as I can tell. Are you compiling on Windows? If so, you can use the libjasper I provide on the Release page in the third-party.zip (most recent one). If on Linux, I compiled it last week on Ubuntu 16.04, the libjasper included in the repositories seemed to work fine.

**Comment by pisarik** [comment]
Yeah, with Jasper 2.0.0 all is good. 

I've made several tests and found out that in version 2.0.0 the opportunity to generate shared libraries was disabled, because it not properly worked on Windows.

However, in Jasper 2.0.10 shared libraries enabled by default, but seems they still not working. 
Jasper 2.0.10 with static linking successfully compiling in `multiresolutionimageinterface` module.
