### ISSUE TITLE
About Stain Specific Standardization

### ISSUE THREAD

**Issue by fukuta0614** [GeertLitjens/ASAP#24]
Hi,
I read your paper about stain specific standardization (https://www.ncbi.nlm.nih.gov/labs/articles/26353368/)
, and I found that the code is implemented in this ASAP.

Would you tell me how to try your code??
Thanks a lot!

**Comment by GeertLitjens** [comment]
Dear Fukuta,

Due to dependence on proprietary code, the stain normalization is not open source. We do share binaries within a research setting. You can contact my colleague Babak Ehteshami for more details. You can find his e-mail on our group website: www.diagnijmegen.nl, under People.

**Comment by fukuta0614** [comment]
I understand.
Thank you so much.
