### ISSUE TITLE
label of annotation groups and color of mask file

### ISSUE THREAD

**Issue by joneww** [GeertLitjens/ASAP#27]
could you tell me something about the rule of generating a mask file.Because i have no idea of giving a label to my annotation groups,when i save the annotation to a mask file by selecting the save file types as tif. If I don't describe my question clearly, please inform me,thank you!

**Comment by GeertLitjens** [comment]
You should put your annotations in groups, where each group can be assigned a numerical label through the GUI of ASAP when saving as TIFF. When generating the mask, each annotation in the group will result in a masked area with that label.

**Comment by joneww** [comment]
When i read the data from the mask file, i found the numerical label. So,thank you for your answer very much.
