### ISSUE TITLE
Kubuntu 16.04 build, missing jpeglib8.h

### ISSUE THREAD

**Issue by sullivak-kyra** [GeertLitjens/ASAP#29]
Hi, I'm running into a problem building on Kubuntu 16.04:
```
io/multiresolutionimageinterface/VSIImage.cpp:14:44: fatal error: dcmtk/dcmjpeg/libijg8/jpeglib8.h: No such file or directory
 #include "dcmtk/dcmjpeg/libijg8/jpeglib8.h"
```
I installed the libdcmtk-dev package (xenial 3.6.1~20150924-5), but /usr/include/dcmtk/dcmjpeg doesn't have a libijg8 dir, just a bunch of header files, and I can't find a jpeglib8.h file anywhere. Any recommendations? Thanks!

**Comment by GeertLitjens** [comment]
You will need to download the source of DCMTK for this header file as well, it is not included in the distribution.

I will be adding a CMake flag which will not compile lossless JPEG support by default so you will not need this anymore.

**Comment by sullivak-kyra** [comment]
Thanks, copying in fixed it!
