### ISSUE TITLE
 error: in C++98 ‘pathology::ColorLookupTables’ must be initialized by constructor, not by ‘{...}’

### ISSUE THREAD

**Issue by weiliu620** [GeertLitjens/ASAP#3]
I got this error when trying to build the latest Github version. I'm using Ubuntu 14.04 LTS 64 bit. 

[  3%] Building CXX object core/CMakeFiles/core.dir/PathologyEnums.cpp.o
/home/weiliu/packages/ASAP/core/PathologyEnums.cpp:12:3: error: in C++98 ‘pathology::ColorLookupTables’ must be initialized by constructor, not by ‘{...}’
   };
   ^
/home/weiliu/packages/ASAP/core/PathologyEnums.cpp:12:3: warning: extended initializer lists only available with -std=c++11 or -std=gnu++11 [enabled by default]

**Comment by weiliu620** [comment]
after change the compiler flag in cmake, I'm able to build no errors.

**Comment by CaseyConger** [comment]
Hi what compiler flag did you add?

**Comment by lalonderodney** [comment]
Adding the line

`set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -g -Wall -std=gnu++11")`

to CMakeLists.txt near the top (just under the project line) fixed it for me.
