### ISSUE TITLE
Problem on opening regular TIFFs

### ISSUE THREAD

**Issue by scarletvv** [GeertLitjens/ASAP#30]
Hi,

I tried to open regular TIFFs  using ASAP 1.7.2, but ASAP crashed immediately after I chose the image file on both Windows and Ubuntu (installed the provided .exe and .deb files).  I attached the image file which I tried to open (01.zip). Does ASAP support the uploaded image file format or not?

 
[01.zip](https://github.com/GeertLitjens/ASAP/files/867378/01.zip)

**Comment by GeertLitjens** [comment]
Dear scarletvv,

No, we do not support regular, non-tiled, single resolution TIFF files at the moment
