### ISSUE TITLE
Errors about Compiling ASAP with VS2015

### ISSUE THREAD

**Issue by githubgzc** [GeertLitjens/ASAP#31]
Hello,
I met some errors about compiling ASAS with VS2015
Error	LNK1181  cannot open input file '..\Release\ASAP.lib'	
Error	LNK1181	cannot open input file '..\..\imgproc\wholeslide\Release\wholeslidefilters.lib'	
Could someone tell me how to solve these errors?
Thanks

**Comment by GeertLitjens** [comment]
I'm sorry, I never tried compiling it with VS2015 yet, it seems some libraries are not compiled. Can you check whether these exist in your build directory?
