### ISSUE TITLE
Display problem of ASAP 1.7.2 on Ubuntu

### ISSUE THREAD

**Issue by scarletvv** [GeertLitjens/ASAP#33]
Hi,

I am using ASAP 1.7.2 on Ubuntu, but having the display problem as shown in the following screen shot. It is happening on every .tif image on Ubuntu. 

![screenshot_v1 7 2](https://cloud.githubusercontent.com/assets/26537299/24846765/51bca074-1def-11e7-986f-22501e23ce76.png)

Thanks,
scarletvv

**Comment by GeertLitjens** [comment]
Hi, my guess is you are under Ubuntu 16.04 or older? The Ubuntu repositories in those version have too old libopenslide packages. I recommend using 16.10 or newer. Some alternative instructions on how to fix it:

https://github.com/GeertLitjens/ASAP/issues/23

and

https://groups.google.com/forum/#!topic/camelyon/6m8LRlYelXA

**Comment by hmkim** [comment]
I solved this issue using 1.9 version of ASAP.
