### ISSUE TITLE
Is there anyway to extract the nuclei detected results as annotations or RGB files?

### ISSUE THREAD

**Issue by hbkunn** [GeertLitjens/ASAP#36]
Is the nuclei detection function python supported?

I'll appreciate it if you could answer my question :)

**Comment by GeertLitjens** [comment]
Hi, yes, you can use it from Python via de wsifilters.NucleiDetectionWholeSlideFilter class which processes an entire slide. Please note that currently it will perform an automated color deconvolution if the input is RGB and this is not yet configurable. You could try to add that yourself in the C++ code. All parameters are set via setter and getter functions. You can look at the C++ header for details

**Comment by hbkunn** [comment]
thank you very much!
