### ISSUE TITLE
could not find JPEG_LIBRARY  and JPEG_INCLUDE_DIR

### ISSUE THREAD

**Issue by FreeAJust** [GeertLitjens/ASAP#37]
I'm trying to compile ASAP in Win10,VS2013.
I am confused with the link offered (http://libjpeg.sourceforge.net/).
I can't process the files that it link to. There are just some cpp files  and I do not know how to set  JPEG_LIBRARY and JPEG_INCLUDE_DIR ?

There are the output messages:
CMake Error at C:/Program Files/CMake/share/cmake-3.8/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find JPEG (missing: JPEG_LIBRARY JPEG_INCLUDE_DIR)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.8/Modules/FindPackageHandleStandardArgs.cmake:377 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.8/Modules/FindJPEG.cmake:30 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:48 (FIND_PACKAGE)

Thanks very much if anyone can help!

**Comment by GeertLitjens** [comment]
You either need to compile libjpeg yourself or download this file which contains most thirdparty dependencies for ASAP on Windows: https://github.com/GeertLitjens/ASAP/releases/download/1.6/ThirdParty.7z
