### ISSUE TITLE
Where are pre-built binaries for Windows and Linux ?

### ISSUE THREAD

**Issue by guruswaroop** [GeertLitjens/ASAP#38]
The documentation says :

> The easiest way to install the software is to download the binary installer or .DEB package from the release page.

But, where is this release page. Can you please provide a link to that. @GeertLitjens

**Comment by GeertLitjens** [comment]
You can find the link on the GitHub front page of the project. For your convience: https://github.com/GeertLitjens/ASAP/releases

**Comment by guruswaroop** [comment]
Thanks a lot !
