### ISSUE TITLE
where is the viewer

### ISSUE THREAD

**Issue by weiliu620** [GeertLitjens/ASAP#4]
I've successfully built it with cmake under Ubuntu 14.04 LTS, but could not find any binary executubles. I used the default settings of cmake, which means all 4 flags are turned off: 

BUILD_DIAG_PATHOLOGY_EXECUTABL   OFF                                                                                                                                                         
 BUILD_DIAG_PATHOLOGY_IMAGEPROC   OFF                                                                                                                                                         
 BUILD_DIAG_PATHOLOGY_TESTS       OFF                                                                                                                                                         
 BUILD_DIAG_PATHOLOGY_WORKSTATI   OFF 

Do I need to turn on first flag to build the viewer? I did but got an error, but that will be another issue that I will open.

**Comment by weiliu620** [comment]
Found it after I build the 'workstation'.

**Comment by fanser** [comment]
Hi, I  also don't find the viewer after I change the 'workstation' flag to  ON. Could you tell me where can I find the viewer?
Thanks!
