### ISSUE TITLE
invalid file type

### ISSUE THREAD

**Issue by chansigit** [GeertLitjens/ASAP#41]
I successfully build the solution but when I use the binary (ASAP_d.exe) to open a tiff file, the software hints "invalid file type" in the bar below. I have successfully opened this file with the distribution provided by your repository so this tiff is a valid file.
What could be the possible cause of it? Thank you for your attention.

Note that I have changed several projects' library option from Dynamic(dll) to Static(lib) in Visual Studio Properties Panel, otherwise I cannot build it successfully( VS hints unable to find *****.obj files)

**Comment by GeertLitjens** [comment]
The file format support is mostly performed via DLL plugins (located under the fileformats folder after installation). You should not need to build anything statically, then something else is going wrong.

**Comment by wjxcsu** [comment]
I have the same problem.I download the ASAP-1.7-win64.exe and try to open the Test Data form http://openslide.org/formats/generic-tiff/ the software hints "invalid file type" in the bar below.  I really do not know how to solve it....

**Comment by GeertLitjens** [comment]
I released a new version in which these type of TIFFs should be working. Please let me know if this is not the case.
