### ISSUE TITLE
boost library link error while compiling asap with vs2013 /WIN7

### ISSUE THREAD

**Issue by landlee001** [GeertLitjens/ASAP#42]
When building asap on WINDOWS,  some errors like below are encountered：
I searched for "_ITERATOR_DEBUG_LEVEL" error, and rebuild boost as debug, but error is still existing. I need help about this.  Thanks 

》build info
system:  WIN7
compile tools : visual studio 2013 community
boost version: 1.64.0
boost build command: b2.exe --prefix=C:\Boost --build-type=complete --build-dir=output address-model=64 runtime-link=static variant=debug stage
ASAP source version：1.7.2

》error info:
2>libboost_filesystem-vc120-mt-s-1_64.lib(path_traits.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in filetools.obj
2>libboost_filesystem-vc120-mt-s-1_64.lib(path_traits.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MDd_DynamicDebug' in filetools.obj
2>libboost_filesystem-vc120-mt-s-1_64.lib(path.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in filetools.obj
2>libboost_filesystem-vc120-mt-s-1_64.lib(path.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MDd_DynamicDebug' in filetools.obj
2>libboost_filesystem-vc120-mt-s-1_64.lib(operations.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in filetools.obj
2>libboost_filesystem-vc120-mt-s-1_64.lib(operations.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MDd_DynamicDebug' in filetools.obj
2>libboost_filesystem-vc120-mt-s-1_64.lib(codecvt_error_category.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in filetools.obj
2>libboost_filesystem-vc120-mt-s-1_64.lib(codecvt_error_category.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MDd_DynamicDebug' in filetools.obj
2>libboost_filesystem-vc120-mt-s-1_64.lib(windows_file_codecvt.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in filetools.obj
2>libboost_filesystem-vc120-mt-s-1_64.lib(windows_file_codecvt.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MDd_DynamicDebug' in filetools.obj
2>libboost_system-vc120-mt-s-1_64.lib(error_code.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in filetools.obj
2>libboost_system-vc120-mt-s-1_64.lib(error_code.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MDd_DynamicDebug' in filetools.obj
2>libboost_regex-vc120-mt-s-1_64.lib(instances.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in filetools.obj
2>libboost_regex-vc120-mt-s-1_64.lib(instances.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MDd_DynamicDebug' in filetools.obj
2>libboost_regex-vc120-mt-s-1_64.lib(regex.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in filetools.obj
2>libboost_regex-vc120-mt-s-1_64.lib(regex.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MDd_DynamicDebug' in filetools.obj
2>libboost_regex-vc120-mt-s-1_64.lib(regex_traits_defaults.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in filetools.obj
2>libboost_regex-vc120-mt-s-1_64.lib(regex_traits_defaults.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MDd_DynamicDebug' in filetools.obj
2>libboost_regex-vc120-mt-s-1_64.lib(static_mutex.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in filetools.obj
2>libboost_regex-vc120-mt-s-1_64.lib(static_mutex.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MDd_DynamicDebug' in filetools.obj
2>libboost_regex-vc120-mt-s-1_64.lib(w32_regex_traits.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in filetools.obj
2>libboost_regex-vc120-mt-s-1_64.lib(w32_regex_traits.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MDd_DynamicDebug' in filetools.obj
2>libboost_regex-vc120-mt-s-1_64.lib(regex_raw_buffer.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in filetools.obj
2>libboost_regex-vc120-mt-s-1_64.lib(regex_raw_buffer.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MDd_DynamicDebug' in filetools.obj
2>msvcprtd.lib(MSVCP120D.dll) : error LNK2005: "public: __cdecl std::locale::id::id(unsigned __int64)" (??0id@locale@std@@QEAA@_K@Z) already defined in libboost_filesystem-vc120-mt-s-1_64.lib(path_traits.obj)
2>msvcprtd.lib(MSVCP120D.dll) : error LNK2005: "public: __cdecl std::locale::id::operator unsigned __int64(void)" (??Bid@locale@std@@QEAA_KXZ) already defined in libboost_filesystem-vc120-mt-s-1_64.lib(path.obj)

**Comment by GeertLitjens** [comment]
It seems that you are trying to use static boost libraries. That could be the issue. I would recommend just to use the pre-built binaries from https://sourceforge.net/projects/boost/files/boost-binaries/1.64.0/. Don't forget to rename the folder containing the DLL files to 'lib' (without quotes) otherwise CMake will not be able to find the files.

**Comment by landlee001** [comment]
Thanks very much. it works.
