### ISSUE TITLE
Compile ASAP in release mode with VS2013,  openslide lib not ok

### ISSUE THREAD

**Issue by landlee001** [GeertLitjens/ASAP#43]
Hi, GeertLitjens, thanks for your last help.  I'v succeeded in introducing support for a new scanning device in ASAP, primarily by modifying openslide library.  It works well in WIN7 system
    But when I install it to WIN10 system, it reports errors that need  MSVCR120D.dll and so on.  So I've to compile ASAP in release version.  And I meet a problem in release version, unable to analysis libopenslide-0.dll by dumpbin.exe, erro info below: 
    "LINK :  fatal error LNK1328: missing string table "
    And when I user original openslide source to compile, the problem remain appears. What's wrong with it? 

》Detail error information is below:

11>  -- fixup_bundle
11>  --   app='D:/Application/ASAP_new/bin/ASAP.exe'
11>  --   libs='D:/Application/ASAP_new/bin/libEGL.dll;D:/Application/ASAP_new/bin/Qt5OpenGL.dll;D:/Application/ASAP_new/bin/plugins/filters/NucleiDetectionFilterPlugin.dll;D:/Application/ASAP_new/bin/formats/openslidefileformat.dll'
11>  --   dirs='D:/Applib/Qt5.6.2/5.6/msvc2013_64/lib/cmake/Qt5/../../../bin;D:/Applib/opencv-3.1.0/build/x64/vc12/lib/../bin;D:/Applib/ThirdParty/openslide/include/openslide/../../bin;D:/Applib/ThirdParty/pugixml/include/../bin;D:/Applib/ThirdParty/unittest/include/UnitTest++/../bin;D:/Applib/boost_1_64_0/lib64-msvc-12.0'
11>  --   ignoreItems=''
11>  -- fixup_bundle: preparing...
11>  -- [DBG] gp_cmd=D:/Application/Microsoft Visual Studio 12.0/VC/bin/x86_amd64/dumpbin.exe; gp_cmd_args=/dependents; target=D:/Applib/ThirdParty/openslide/bin/libopenslide-0.dll; gp_cmd_maybe_filter=
11>  CMake Error at D:/Application/Cmake/share/cmake-3.9/Modules/GetPrerequisites.cmake:838 (message):
11>    D:/Application/Microsoft Visual Studio 12.0/VC/bin/x86_amd64/dumpbin.exe
11>    failed: 1328
11>  
11>    
11>  
11>    Microsoft (R) COFF/PE Dumper Version 12.00.31101.0
11>  
11>    Copyright (C) Microsoft Corporation.  All rights reserved.
11>  
11>    
11>  
11>    
11>  
11>    Dump of file D:/Applib/ThirdParty/openslide/bin/libopenslide-0.dll
11>  
11>    
11>  
11>    File Type: DLL
11>  
11>    
11>  
11>      Image has the following dependencies:
11>  
11>    
11>  
11>        libcairo-2.dll
11>        libgdk_pixbuf-2.0-0.dll
11>        libgio-2.0-0.dll
11>        libglib-2.0-0.dll
11>        libgobject-2.0-0.dll
11>        libjpeg-62.dll
11>        libopenjp2.dll
11>        libpng16-16.dll
11>        libsqlite3-0.dll
11>        libtiff-5.dll
11>        libxml2-2.dll
11>        zlib1.dll
11>        KERNEL32.dll
11>        msvcrt.dll
11>  
11>LINK : fatal error LNK1328: missing string table
11>  
11>  Call Stack (most recent call first):
11>    D:/Application/Cmake/share/cmake-3.9/Modules/GetPrerequisites.cmake:969 (get_prerequisites)
11>    D:/Application/Cmake/share/cmake-3.9/Modules/BundleUtilities.cmake:585 (get_prerequisites)
11>    D:/Application/Cmake/share/cmake-3.9/Modules/BundleUtilities.cmake:903 (get_bundle_keys)
11>    buildtools/cmake_install.cmake:83 (fixup_bundle)
11>    cmake_install.cmake:81 (include)
11>  
11>  
11>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073: The command "setlocal
11>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073: D:\Application\Cmake\bin\cmake.exe -DBUILD_TYPE=Release -P cmake_install.cmake
11>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd
11>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073: :cmEnd
11>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073: endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
11>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073: :cmErrorLevel
11>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073: exit /b %1
11>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073: :cmDone
11>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073: if %errorlevel% neq 0 goto :VCEnd
11>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073: :VCEnd" exited with code 1.

**Comment by GeertLitjens** [comment]
It is because OpenSlide strips the symbols from the DLLs. You need to edit the build.sh file for OpenSlide and modify${build_host}-objcopy -S  and change it to ${build_host}-objcopy -g. That fixes this issue.

**Comment by landlee001** [comment]
exactly, thanks a lot
