### ISSUE TITLE
invaild file type

### ISSUE THREAD

**Issue by wjxcsu** [GeertLitjens/ASAP#44]
# invalid file type
I use win10 64bit.I download the released ASAP ,ASAP-1.7-win64.exe and install it.I also download Test Data  CMU-1.tiff form http://openslide.org/formats/generic-tiff/ .Then I use ASAP to open the CMU-1.tiff but software hints "invalid file type" in the bar below.
I was troubled by this problem for a few days.Can you tell me how to solve it?
Thanks a lot!!

**Comment by GeertLitjens** [comment]
Should be fixed in latest release.
