### ISSUE TITLE
build error with boost

### ISSUE THREAD

**Issue by landlee001** [GeertLitjens/ASAP#45]
Hi, Geert. I'm sorry to bother you again.  
For some reason, I cleaned my VS2013 project generated by CMAKE, and executed CMAKE again, but something is wrong with the new VS2013 project. I got warnings and errors like below. I googled some answers but they does not work well. Could you help me? Thanks a lot.

》boost config for CMAKE
Boost_DEBUG=ON
Boost_NO_BOOST_CMAKE=ON
Boost_USE_STATIC_LIBS=ON
BOOST_ROOT=D:/Applib/boost_1_64_0
BOOST_INCLUDE_DIR=D:/Applib/boost_1_64_0

》Boost library is found OK by CMAKE, detailed log while configuring cmake:
Boost version: 1.64.0
Found the following Boost libraries:
  date_time
  filesystem
  program_options
  regex
  system
  thread
  chrono
  atomic

》detailed warnings 
`1>MultiResImageConverter.obj : warning LNK4217: locally defined symbol ??0validation_error@program_options@boost@@QEAA@W4kind_t@012@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@1H@Z (public: __cdecl boost::program_options::validation_error::validation_error(enum boost::program_options::validation_error::kind_t,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,int)) imported in function "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const & __cdecl boost::program_options::validators::get_single_string<char>(class std::vector<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > const &,bool)" (??$get_single_string@D@validators@program_options@boost@@YAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@4@_N@Z)
`

》detailed errors
1>MultiResImageConverter.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl boost::program_options::invalid_option_value::invalid_option_value(class boost::program_options::invalid_option_value const &)" (__imp_??0invalid_option_value@program_options@boost@@QEAA@AEBV012@@Z) referenced in function "struct boost::exception_detail::error_info_injector<class boost::program_options::invalid_option_value> __cdecl boost::enable_error_info<class boost::program_options::invalid_option_value>(class boost::program_options::invalid_option_value const &)" (??$enable_error_info@Vinvalid_option_value@program_options@boost@@@boost@@YA?AU?$error_info_injector@Vinvalid_option_value@program_options@boost@@@exception_detail@0@AEBVinvalid_option_value@program_options@0@@Z)

**Comment by GeertLitjens** [comment]
Seems like it is not linking the boost_program_options library. Could you check you CMake to make sure the boost libraries are found correctly? Probably they are under the advanced options

**Comment by GeertLitjens** [comment]
Hmm, I also never tried to link boost statically, so that might also be an issue.

**Comment by landlee001** [comment]
Exactly right! Setting Boost_USE_STATIC_LIBS=OFF resolves this problem. Maybe I changed this CMAKE config after cleaning the former VS project.
Thanks very very much. :)
