### ISSUE TITLE
open.tif

### ISSUE THREAD

**Issue by tianoak** [GeertLitjens/ASAP#46]
There are duplicate fragments on the border of the image opened, but after I zoom it, the repetition disappears. I generate that.tif image by convert .jpeg using Imagemagick.

**Comment by tianoak** [comment]
I see some similar problems in other issues, however I directly use your compiled version ASAP 1.7.2 on windows. P.S. The border I said means right and down side.

**Comment by GeertLitjens** [comment]
I don't know how the conversion is exactly done. Usually these kind of artifacts appear due to the fact there are tiles at the edges of the images that are not competely filled. I'm not sure whether this is an ASAP bug or a conversion issue.
