### ISSUE TITLE
cannot load xml file after pressing Load button

### ISSUE THREAD

**Issue by tt-leader** [GeertLitjens/ASAP#49]
When I use ASAP to view Hamamatsu ndpi WSI files, I cannot load annotation files in the folder. ASAP used a file extension name filter, it only accept .xml file and .ndpa file, but I cannot see my .xml file when I pressed Load button. However, when I pressed Save button, I can see xml file in the folder.

Anybody can help me? Thank you.

Version: 1.7.3
Platform: Ubuntu 16.04
install by deb file

**Comment by GeertLitjens** [comment]
I will look into, you can work around it for now by typing a * in the filename section of the 'open file'-dialog you get when pressing load and pressing enter, this should at least show you all files.

**Comment by tt-leader** [comment]
@GeertLitjens I typed * in the filename section, it tells me 
`*`
`File not found`
`Please verify the correct file name was given`

However, I found I can type the annotation whole filename in the filename section and press enter, it works.
