### ISSUE TITLE
Ubuntu 14.04 package possible?

### ISSUE THREAD

**Issue by dhmurph** [GeertLitjens/ASAP#52]
Hello GeertLitjens and community,

I would love to use ASAP, but trying to install via the .deb file on Ubuntu 14.04 fails because several dependencies (e.g. libboost-filesystem1.58) are not available on 14.04 (requires 16.04).

If ASAP's functionality doesn't depend on the version of the uninstallable packages, would you mind compiling against the lower versions?  A list of the uninstallable ones is below.

Thanks!

Dennis

The following packages have unmet dependencies:
 asap : Depends: libboost-filesystem1.58.0 but it is not installable
        Depends: libboost-program-options1.58.0 but it is not installable
        Depends: libboost-regex1.58.0 but it is not installable
        Depends: libboost-system1.58.0 but it is not installable
        Depends: libboost-thread1.58.0 but it is not installable
        Depends: libdcmtk5 but it is not installable
        Depends: libpugixml1v5 (>= 1.7) but it is not installable
        Depends: libpython3.5 (>= 3.5.0~b1) but it is not installable

        ------------------------

        Depends: libqt5core5a (>= 5.5.0) but 5.2.1+dfsg-1ubuntu14.3 is installed
        Depends: libqt5gui5 (>= 5.3.0) but 5.2.1+dfsg-1ubuntu14.3 is installed or
                 libqt5gui5-gles (>= 5.3.0) but it is not installable
        Depends: libqt5widgets5 (>= 5.3.0) but 5.2.1+dfsg-1ubuntu14.3 is installed
        Depends: libstdc++6 (>= 5.2) but 4.8.4-2ubuntu1~14.04.3 is installed

**Comment by GeertLitjens** [comment]
I'm sorry, we don't have the manpower to support multiple versions for the differing operating systems. I recommend you either upgrade to Ubuntu 16.04, or compile ASAP yourself, it should be relatively straightforward.
