### ISSUE TITLE
How to set Variable "UNITTEST_LIBRARY_DEBUG" and "UNITTEST_LIBRARY"

### ISSUE THREAD

**Issue by hsyi** [GeertLitjens/ASAP#54]
I've set this two variable to point same directory which contains "ibUnitTest++.a"
command "cmake" shows one warning
WARNING: Target "patholTestRunner" requests linking to directory "/usr/local/lib/".  Targets may link only to libraries.  CMake is dropping the item.
and command "make" return error, and it seems that it failed to find unitest++
so my setting should be wrong, can you help me?

**Comment by Tocic** [comment]
Yeah, I also had such messages. Also there were troubles with _includes_ in some files. Try to build my fork with the following (replace _/usr/..._ with _/usr/local/..._ if you need):
```
        cmake . \
          -DOPENSLIDE_INCLUDE_DIR=/usr/include/openslide/ \
          -DUNITTEST_INCLUDE_DIR=/usr/include/UnitTest++ \
          -DUNITTEST_LIBRARY=/usr/lib/libUnitTest++.a \
          -DUNITTEST_LIBRARY_DEBUG=/usr/lib/libUnitTest++.a \
          -DCMAKE_INSTALL_PREFIX=/usr \
          -DBUILD_DIAG_PATHOLOGY_EXECUTABLES=ON \
          -DBUILD_DIAG_PATHOLOGY_WORKSTATION=ON \
          -DBUILD_DIAG_PATHOLOGY_IMAGEPROCESSING=ON \
          -DBUILD_DIAG_PATHOLOGY_TESTS=ON \
          -DBUILD_DIAG_PATHOLOGY_INSTALL=ON

        make
```

**Comment by GeertLitjens** [comment]
These items should not be pointed to a directory, but specifically to the library itself. In your case that is the issue. Note that you cannot use a release libUnittest++ to build debug versions of the test, you will need to get the actual debug library for that.

**Comment by hsyi** [comment]
Thank you!my problem has been solved.
