### ISSUE TITLE
ASAP and python

### ISSUE THREAD

**Issue by FrPo** [GeertLitjens/ASAP#56]
I would like to ask if it is possible to extend ASAP functionalities with plug-in based on python. I'm interested in creating some functionality to manage automatic slide cropping.
I was wondering if i need to work with c++ or may i use python.

Thank you,
Francesco Ponzio

**Comment by GeertLitjens** [comment]
Hi, I personally don't think so. You can make plugins in C++ that you can expose in Python, but I don't think you can do the other way around without including a running Python interpreter process.
