### ISSUE TITLE
Make error in some source code

### ISSUE THREAD

**Issue by hzzclau** [GeertLitjens/ASAP#57]
I git the source code and have already installed all third-party libraries. Followed some issues I fix some bug occurred in compile processing.  But when I make it in the program, errors coming. At First I add "#include<cmath>" to fix some problems. But I can not fix this:
`Building CXX object imgproc/wholeslide/CMakeFiles/wholeslidefilters.dir/NucleiDetectionWholeSlideFilter.cpp.o
In file included from /Users/chengluzhu/Gits/ASAP/imgproc/wholeslide/NucleiDetectionWholeSlideFilter.cpp:2:
In file included from /Users/chengluzhu/Gits/ASAP/io/multiresolutionimageinterface/MultiResolutionImage.h:9:
In file included from /Users/chengluzhu/Gits/ASAP/core/Patch.h:69:
/Users/chengluzhu/Gits/ASAP/core/Patch.hpp:219:21: error: binding value of type 'const Patch<...>' to
      reference to type 'Patch<...>' drops 'const' qualifier
  this->swap(*this, rhs);
                    ^~~
`
My system is maxos

**Comment by GeertLitjens** [comment]
Hi hzzclau. I'm sorry, we currently don't provide support for macOS as we do not have those machines available for development. As such it is impossible for me to provide support for this platform at this time.
