### ISSUE TITLE
make processing error in /core/Patch.hpp:219:21

### ISSUE THREAD

**Issue by hzzclau** [GeertLitjens/ASAP#58]
I set  BUILD_DIAG_PATHOLOGY_IMAGEPROC and BUILD_MULTIRESOLUTIONIMAGEINTE to ON, then I want to use it in python and I set WRAP_MULTIRESOLUTIONIMAGEINTER and WRAP_WHOLESLIDEFILTERS_PYTHON to ON. And I began to cmake and make this and finnally the error occurred  at 93% processing followed:
In file included from ~/ASAP/imgproc/wholeslide/NucleiDetectionWholeSlideFilter.cpp:2: 
In file included from ~/ASAP/io/multiresolutionimageinterface/MultiResolutionImage.h:9:
In file included from ~/ASAP/core/Patch.h:69:
~/ASAP/core/Patch.hpp:219:21: error: binding value of type 'const Patch<...>' to
      reference to type 'Patch<...>' drops 'const' qualifier
  this->swap(*this, rhs);

So what can I do for fix it?

**Comment by GeertLitjens** [comment]
Like I said in the previous issue, I cannot help you with compilation on OS/x. Most likely you are using a different compiler (clang maybe) than we do under Linux and Windows. As I don't have an Apple machine to test with, I cannot reproduce your error and help you fix it. I'll leave this issue open for now, so if somebody else can help you they can respond here.

**Comment by hzzclau** [comment]
I have tried to fix those errors occurred in the compiling, but it still failed. Now I install dual OS of Ubuntu 16.04 to use your code first. I hope someone can fix these in maxOS . Thanks for helping!
