### ISSUE TITLE
non-existent target "opencv_world".

### ISSUE THREAD

**Issue by LiamHou** [GeertLitjens/ASAP#60]
CMake Warning (dev) at buildtools/CMakeLists.txt:7 (get_target_property):
  Policy CMP0045 is not set: Error on non-existent target in
  get_target_property.  Run "cmake --help-policy CMP0045" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  get_target_property() called with non-existent target "opencv_world".
This warning is for project developers.  Use -Wno-dev to suppress it.

**Comment by GeertLitjens** [comment]
I'm guessing you are not using OpenCV version 3.1 or newer
