### ISSUE TITLE
dynamic module does not define init function

### ISSUE THREAD

**Issue by wangyxcv** [GeertLitjens/ASAP#61]
Hi，I have installed ASPA in ubuntu 14.04 by compiling the source code. But when I try to import the module multiresolutionimageinterface, I got 'ImportError: dynamic module does not define init function (init_multiresolutionimageinterface)'. What is the problem in my installation?

**Comment by GeertLitjens** [comment]
It is impossible to tell given this information, it could be issues with Swig, or compilation, or mixing Python versions.

**Comment by wangyxcv** [comment]
I use the cmake with version 3.10.1. But I notice that I got the following message when compiling.

 CMake Deprecation Warning at /usr/local/share/cmake-3.10/Modules/UseSWIG.cmake:231 (message):
  SWIG_ADD_MODULE is deprecated.  Use SWIG_ADD_LIBRARY instead.
Call Stack (most recent call first):
  io/multiresolutionimageinterface/CMakeLists.txt:134 (SWIG_ADD_MODULE)

Does it make the problem?

**Comment by GeertLitjens** [comment]
No, that shouldn't matter.

**Comment by wangyxcv** [comment]
I have found the problem. My ASAP is depend on the python3.5. But I try to import multiresolutionimageinterface using python2.7. 

Thank you so much!
