### ISSUE TITLE
Is there a plan to support bioformats ?

### ISSUE THREAD

**Issue by artzers** [GeertLitjens/ASAP#62]
Hello, we are processing some medical image, of which the format is bigtiff(not pyramid) or VSI (olympus virtual slide image, not whole slide image). Do you have any plan to support bio formats ? Then this software can be used widely.

**Comment by GeertLitjens** [comment]
I would like to support it and look at it in the near future.

**Comment by GeertLitjens** [comment]
Bioformats discontinued support for their C++ bindings and their new C++-bioformats version still needs a lot of development. So I'll close this for now.
