### ISSUE TITLE
ASAP 1.7.3 linux version not working correctly

### ISSUE THREAD

**Issue by min6434** [GeertLitjens/ASAP#63]
I am using ubuntu 16.04 OS and installed ASAP 1.7.3 
I tried opening Camelyon16 data from the google drive, but noting happened with ASAP.exe.
I tried windows version with other PC which works fine.

**Comment by GeertLitjens** [comment]
You could try the new 1.7.4 release, that might fix the issue. Pleas notee that you do need OpenSlide version 3.4.1 installed, this is not present in the default Ubuntu 16.04 repos, only in 16.10 and newer.

**Comment by min6434** [comment]
Thank you for your support
I had the same invalid file type error above.
Now I installed OpenSlide as you said, and I can see the image, but image is not shown correctly.
![screenshot from 2018-02-20 15-59-06](https://user-images.githubusercontent.com/25948850/36411065-388aacc0-1657-11e8-8397-ad72464a13b6.png)

**Comment by GeertLitjens** [comment]
You probably have the wrong version. You need to have OpenSlide 3.4.1, not 3.4.0 to read the Philips TIFF format, which is not in the default Ubuntu 16.04 repositories.

**Comment by Peter554** [comment]
Yes after installing openslide manually (I was trying to use it with some C code) it now all works fine
