### ISSUE TITLE
Upper Left panel (Annotations) is not resizable

### ISSUE THREAD

**Issue by shizhaojingszj** [GeertLitjens/ASAP#64]
Affect version: 1.7.3

It would be nice if the **upper left panel can be resized by users**, especially when the lower left area is usually empty. 

When there are many annotations, scrollbar is not enough.

**Comment by GeertLitjens** [comment]
It can be resized if you put your mouse cursor just below the buttons

**Comment by shizhaojingszj** [comment]
Oh my, shamed for this silly question...

Thank you.
