### ISSUE TITLE
Custom annotation colors cannot be saved

### ISSUE THREAD

**Issue by shizhaojingszj** [GeertLitjens/ASAP#65]
Affect version: 1.7.3

After quiting and restarting, all my custom colors are lost.

Maybe there is a way to save the last preference?

**Comment by shizhaojingszj** [comment]
Is there any plan to fix this, it is really inconvenient to relabel all the custom colors we used after software reboot.

**Comment by GeertLitjens** [comment]
If it is urgent you can of course do this yourself (it is opens-source
after all) and commit it to the repository, I could provide some guidance
on how to do that if you need help.

**Comment by GeertLitjens** [comment]
Annotations custom colors are now persistent in 1.8
