### ISSUE TITLE
Cannot open file with non-ASCII path

### ISSUE THREAD

**Issue by shizhaojingszj** [GeertLitjens/ASAP#66]
Affect Version: 1.7.3

Good:
        /a/good/file/to/open.ndpi

Bad:
        /一个打不开/file.ndpi

I'm Chinese, huge thanks for your work! But it would be nice if ASAP support non-ASCII characters when importing a file.

**Comment by GeertLitjens** [comment]
I will look at this for the next release

**Comment by GeertLitjens** [comment]
This should work in 1.8
