### ISSUE TITLE
'Invalid file type' error Ubuntu 16.04LTS

### ISSUE THREAD

**Issue by Peter554** [GeertLitjens/ASAP#67]
So I downloaded the latest release:
**```ASAP-1.7-Linux-python35.deb```**
and installed using ```sudo apt install ./ASAP-1.7-Linux-python35.deb```.
To run ASAP I then do  ```/opt/ASAP/bin/ASAP``` which appears to open ASAP correctly. 
I then tried to open a .tif file (from Camelyon 16 dataset) and also a .ndpi file. For both of these I get an **'invalid file type'** error. I am running Ubuntu 16.04LTS and using Python 3.5 in a conda environment. Any idea what the problem could be? I'm rather confused as I have a laptop also running Ubuntu 16.04LTS with Python 3.5 (conda environment) and ASAP seems to be working OK on that one (at least it opens these same files..)

**Comment by min6434** [comment]
You should install OpenSlide.
I can see the image after installing them.
