### ISSUE TITLE
Documentation: how best to convert xml annotation files to tif masks?

### ISSUE THREAD

**Issue by Peter554** [GeertLitjens/ASAP#68]
I wonder if the documentation could be extended to detail best practice when converting xml annotations to (e.g. .tif) masks? It's not at present clear to me how to do this?

**Comment by GeertLitjens** [comment]
Hi, documentation is something we are working on. You can do it via ASAP by saving the annotations as a TIFF. You can then assign a label per annotation group

**Comment by Peter554** [comment]
Thanks yes it's actually very easy! Great Software!
