### ISSUE TITLE
Use ASAP open .tif file crash

### ISSUE THREAD

**Issue by DaihuaWei** [GeertLitjens/ASAP#69]
when i use the ASAP open the CAMELYON17 data, the pathology photo appears some micro second, and then disappear. who can tell me the reason? thanks

**Comment by GeertLitjens** [comment]
I have no idea, are you sure you have correctly installed all dependencies and are using the latest version? Are you using it on Windows or Linux? If on Linux, you need OpenSlide 3.4.1 installed.
