### ISSUE TITLE
Annotation loading not working

### ISSUE THREAD

**Issue by Vozf** [GeertLitjens/ASAP#73]
After creating some annotations and saving them to the xml file they cannot be loaded later. The filepicker just doesn't see theese files. It only lists folders and no xml files at all. 
Version 1.7.4
Ubuntu 16.04 lts.
Installed via deb file

**Comment by GeertLitjens** [comment]
Fixed it in the code, the fix will be included in the next release. In the mean time, you can find the XML file by replacing the filter with * or *.xml
