### ISSUE TITLE
Pictures cut using openslide and saved as tif cannot be viewed. Asap crashes

### ISSUE THREAD

**Issue by Vozf** [GeertLitjens/ASAP#74]
I have a 3gb tif image which works with asap. Then i cut it to lesser images of different sizes  and trying to open any of them makes asap crash
Images related https://yadi.sk/d/sj-h-pWx3Tmvev

**Comment by Vozf** [comment]
terminal errors
![image](https://user-images.githubusercontent.com/22998537/38189979-ea6caa6e-366a-11e8-8838-3d6dbacf8e78.png)

**Comment by Vozf** [comment]
As i know saving in openslide utilises a PIL tif  image driver

**Comment by GeertLitjens** [comment]
ASAP does not support striped TIFFs, only tiled TIFFs. It should obviously not crash, so that is something I will try to fix for the next release.
