### ISSUE TITLE
Cannot compile on mac

### ISSUE THREAD

**Issue by artzers** [GeertLitjens/ASAP#75]
Hello, I m trying to compile ASAP on mac os 10.11.6. The Library are : boost 1.55 qt 5.10, other libraries are installed by homebrew. 
The compilation stop at : 
Undefined symbols for architecture x86_64:
  "PathologyViewer::getActiveTool()", referenced from:
      AnnotationWorkstationExtensionPlugin::eventFilter(QObject*, QEvent*) in AnnotationWorkstationExtensionPlugin.cpp.o
  "PathologyViewer::updateCurrentFieldOfView()", referenced from:
      AnnotationTool::zoomToAnnotationFinished() in AnnotationTool.cpp.o
  "vtable for QtProgressMonitor", referenced from:
      QtProgressMonitor::QtProgressMonitor() in AnnotationWorkstationExtensionPlugin.cpp.o
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [ASAP/annotation/libAnnotationPlugin.dylib] Error 1
make[1]: *** [ASAP/annotation/CMakeFiles/AnnotationPlugin.dir/all] Error 2

I have tried to  add "virtual ~QtProgressMonitor(){}"  but still error. It shows "unreferenced symbol to ~QtProgressMonitor(){}". It is very strange. Could you tell me how to do?

**Comment by GeertLitjens** [comment]
Hi, currently I cannot support Mac as a platform as I don't have access to the needed hardware.
