### ISSUE TITLE
Import .CZI file into ASAP

### ISSUE THREAD

**Issue by anyone1985** [GeertLitjens/ASAP#77]
I scaned several slides with Zen Scaner and produced .CZI files. I'd like to know if there is any method to import .CZI file into ASAP. Or, how could I convert the .CZI to read by ASAP?

**Comment by liuzhisheng1226** [comment]
Do you solve your problem?? I need your help,I meet the same problem.

**Comment by GeertLitjens** [comment]
Hi, you could probably convert the CZI to TIFF with BioFormats and then open it in ASAP: https://docs.openmicroscopy.org/bio-formats/5.8.2/users/comlinetools/conversion.html
